package ClientSide;

import java.io.*;
import java.net.*;
import ClientSide.*;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.SQLException;


public class ClientGUI extends javax.swing.JFrame {
    // DBConnection
    DBConnect hotel = new DBConnect();
    
    // Variable for server communication
    
    
    
    //Chosen location by user
    public String chosenLocation;
    
    

    public ClientGUI() {
        
        initComponents();
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewAreaHotels = new javax.swing.JFrame();
        logo2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaHotelsList = new javax.swing.JList<>();
        hotelListLabel = new javax.swing.JLabel();
        selectHotelBtn = new javax.swing.JButton();
        viewHotelRooms = new javax.swing.JFrame();
        logo3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        roomsList = new javax.swing.JList<>();
        selectRoomBtn = new javax.swing.JButton();
        createReservations = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        createResBtn = new javax.swing.JButton();
        NameField = new javax.swing.JTextField();
        createResLabel = new javax.swing.JLabel();
        creditNumField = new javax.swing.JTextField();
        cardCodeField = new javax.swing.JTextField();
        checkInField = new javax.swing.JTextField();
        checkOutField = new javax.swing.JTextField();
        confirmReservations = new javax.swing.JFrame();
        logoSpace = new javax.swing.JPanel();
        logo5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        reservationsLabel = new javax.swing.JLabel();
        roomTypeLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        confirmBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        atLabel = new javax.swing.JLabel();
        reservationsMade = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cusReservationFrame = new javax.swing.JFrame();
        logoSpace1 = new javax.swing.JPanel();
        logo6 = new javax.swing.JLabel();
        searchNameField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        viewReservationBtn = new javax.swing.JButton();
        modifyReservations = new javax.swing.JFrame();
        logoSpace2 = new javax.swing.JPanel();
        logo7 = new javax.swing.JLabel();
        changeCheckInBtn = new javax.swing.JButton();
        cancelReservationsBtn = new javax.swing.JButton();
        changeCheckOutBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        cusReservationsList = new javax.swing.JList<>();
        billBtn = new javax.swing.JButton();
        changeCheckOutFrame = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        logo9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        newCheckOutField = new javax.swing.JTextField();
        confirmChangeCheckOutBtn = new javax.swing.JButton();
        changeCheckInFrame = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        logo8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        newCheckInField = new javax.swing.JTextField();
        confirmChangeCheckInBtn = new javax.swing.JButton();
        successfulChangeFrame = new javax.swing.JFrame();
        jPanel8 = new javax.swing.JPanel();
        logo12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        billFrame = new javax.swing.JFrame();
        logoSpace3 = new javax.swing.JPanel();
        logo10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        canceledRes = new javax.swing.JFrame();
        logoSpace4 = new javax.swing.JPanel();
        logo11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        findHotelsBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cityHotelList = new javax.swing.JList<>();
        haveReservationsBtn = new javax.swing.JButton();

        viewAreaHotels.setMinimumSize(new java.awt.Dimension(400, 400));
        viewAreaHotels.setSize(new java.awt.Dimension(400, 400));

        logo2.setBackground(new java.awt.Color(51, 51, 51));
        logo2.setPreferredSize(new java.awt.Dimension(110, 70));

        jLabel2.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HYATT ");

        javax.swing.GroupLayout logo2Layout = new javax.swing.GroupLayout(logo2);
        logo2.setLayout(logo2Layout);
        logo2Layout.setHorizontalGroup(
            logo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logo2Layout.setVerticalGroup(
            logo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logo2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        areaHotelsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(areaHotelsList);

        hotelListLabel.setText("Here are hotels for your location: ");

        selectHotelBtn.setText("Select");
        selectHotelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectHotelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewAreaHotelsLayout = new javax.swing.GroupLayout(viewAreaHotels.getContentPane());
        viewAreaHotels.getContentPane().setLayout(viewAreaHotelsLayout);
        viewAreaHotelsLayout.setHorizontalGroup(
            viewAreaHotelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo2, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .addGroup(viewAreaHotelsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewAreaHotelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewAreaHotelsLayout.createSequentialGroup()
                        .addComponent(hotelListLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAreaHotelsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(viewAreaHotelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAreaHotelsLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAreaHotelsLayout.createSequentialGroup()
                                .addComponent(selectHotelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(183, 183, 183))))))
        );
        viewAreaHotelsLayout.setVerticalGroup(
            viewAreaHotelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewAreaHotelsLayout.createSequentialGroup()
                .addComponent(logo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hotelListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectHotelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        viewHotelRooms.setSize(new java.awt.Dimension(400, 400));

        logo3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HYATT");

        javax.swing.GroupLayout logo3Layout = new javax.swing.GroupLayout(logo3);
        logo3.setLayout(logo3Layout);
        logo3Layout.setHorizontalGroup(
            logo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logo3Layout.setVerticalGroup(
            logo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logo3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        roomsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(roomsList);

        selectRoomBtn.setText("Select Room");
        selectRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectRoomBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewHotelRoomsLayout = new javax.swing.GroupLayout(viewHotelRooms.getContentPane());
        viewHotelRooms.getContentPane().setLayout(viewHotelRoomsLayout);
        viewHotelRoomsLayout.setHorizontalGroup(
            viewHotelRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewHotelRoomsLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(viewHotelRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewHotelRoomsLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewHotelRoomsLayout.createSequentialGroup()
                        .addComponent(selectRoomBtn)
                        .addGap(136, 136, 136))))
        );
        viewHotelRoomsLayout.setVerticalGroup(
            viewHotelRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewHotelRoomsLayout.createSequentialGroup()
                .addComponent(logo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectRoomBtn)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        createReservations.setSize(new java.awt.Dimension(400, 400));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(103, 70));

        jLabel5.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HYATT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        createResBtn.setText("Create Reservation");
        createResBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createResBtnActionPerformed(evt);
            }
        });

        NameField.setText("Name");
        NameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NameFieldMousePressed(evt);
            }
        });
        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });

        createResLabel.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        createResLabel.setText("Create Reservations...");

        creditNumField.setText("Credit Card Number");
        creditNumField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                creditNumFieldMousePressed(evt);
            }
        });

        cardCodeField.setText("CCV");
        cardCodeField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cardCodeFieldMousePressed(evt);
            }
        });

        checkInField.setText("Check In Date");
        checkInField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                checkInFieldMousePressed(evt);
            }
        });

        checkOutField.setText("Check Out Date");
        checkOutField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                checkOutFieldMousePressed(evt);
            }
        });
        checkOutField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createReservationsLayout = new javax.swing.GroupLayout(createReservations.getContentPane());
        createReservations.getContentPane().setLayout(createReservationsLayout);
        createReservationsLayout.setHorizontalGroup(
            createReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createReservationsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(createResBtn)
                .addGap(118, 118, 118))
            .addGroup(createReservationsLayout.createSequentialGroup()
                .addGroup(createReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createReservationsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(createResLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createReservationsLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(createReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(createReservationsLayout.createSequentialGroup()
                                .addComponent(checkInField, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(checkOutField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NameField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(createReservationsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(creditNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(cardCodeField, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );
        createReservationsLayout.setVerticalGroup(
            createReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createReservationsLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(createResLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkInField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkOutField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(createResBtn)
                .addContainerGap())
        );

        confirmReservations.setMinimumSize(new java.awt.Dimension(400, 400));
        confirmReservations.setSize(new java.awt.Dimension(580, 400));

        logoSpace.setBackground(new java.awt.Color(51, 51, 51));
        logoSpace.setPreferredSize(new java.awt.Dimension(104, 70));

        logo5.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        logo5.setForeground(new java.awt.Color(255, 255, 255));
        logo5.setText("HYATT");

        javax.swing.GroupLayout logoSpaceLayout = new javax.swing.GroupLayout(logoSpace);
        logoSpace.setLayout(logoSpaceLayout);
        logoSpaceLayout.setHorizontalGroup(
            logoSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoSpaceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoSpaceLayout.setVerticalGroup(
            logoSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoSpaceLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logo5)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        nameLabel.setText("Name");

        reservationsLabel.setText("Date");

        roomTypeLabel.setText("Room Type");

        jLabel4.setFont(new java.awt.Font("Al Bayan", 3, 18)); // NOI18N
        jLabel4.setText("Reservations for:");

        jLabel6.setFont(new java.awt.Font("Al Bayan", 3, 18)); // NOI18N
        jLabel6.setText("From:");

        jLabel7.setFont(new java.awt.Font("Al Bayan", 3, 18)); // NOI18N
        jLabel7.setText("Room Type:");

        confirmBtn.setText("Confirm");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Al Bayan", 3, 18)); // NOI18N
        jLabel8.setText("At:");

        atLabel.setText("jLabel9");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(nameLabel)
                    .addComponent(jLabel8)
                    .addComponent(atLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservationsLabel)
                    .addComponent(jLabel6)
                    .addComponent(roomTypeLabel)
                    .addComponent(jLabel7)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reservationsLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomTypeLabel)
                    .addComponent(atLabel))
                .addGap(89, 89, 89)
                .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout confirmReservationsLayout = new javax.swing.GroupLayout(confirmReservations.getContentPane());
        confirmReservations.getContentPane().setLayout(confirmReservationsLayout);
        confirmReservationsLayout.setHorizontalGroup(
            confirmReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoSpace, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
            .addGroup(confirmReservationsLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        confirmReservationsLayout.setVerticalGroup(
            confirmReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmReservationsLayout.createSequentialGroup()
                .addComponent(logoSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        reservationsMade.setSize(new java.awt.Dimension(400, 400));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel9.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("HYATT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(19, 19, 19))
        );

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel10.setText("You Just Made Reservations!");

        javax.swing.GroupLayout reservationsMadeLayout = new javax.swing.GroupLayout(reservationsMade.getContentPane());
        reservationsMade.getContentPane().setLayout(reservationsMadeLayout);
        reservationsMadeLayout.setHorizontalGroup(
            reservationsMadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(reservationsMadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        reservationsMadeLayout.setVerticalGroup(
            reservationsMadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservationsMadeLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        cusReservationFrame.setSize(new java.awt.Dimension(400, 400));

        logoSpace1.setBackground(new java.awt.Color(51, 51, 51));
        logoSpace1.setPreferredSize(new java.awt.Dimension(104, 70));

        logo6.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        logo6.setForeground(new java.awt.Color(255, 255, 255));
        logo6.setText("HYATT");

        javax.swing.GroupLayout logoSpace1Layout = new javax.swing.GroupLayout(logoSpace1);
        logoSpace1.setLayout(logoSpace1Layout);
        logoSpace1Layout.setHorizontalGroup(
            logoSpace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoSpace1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        logoSpace1Layout.setVerticalGroup(
            logoSpace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoSpace1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logo6)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        searchNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNameFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Enter Your Name: ");

        viewReservationBtn.setText("View Your Reservations");
        viewReservationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReservationBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cusReservationFrameLayout = new javax.swing.GroupLayout(cusReservationFrame.getContentPane());
        cusReservationFrame.getContentPane().setLayout(cusReservationFrameLayout);
        cusReservationFrameLayout.setHorizontalGroup(
            cusReservationFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoSpace1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(cusReservationFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cusReservationFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewReservationBtn)
                    .addGroup(cusReservationFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(searchNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cusReservationFrameLayout.setVerticalGroup(
            cusReservationFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusReservationFrameLayout.createSequentialGroup()
                .addComponent(logoSpace1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(viewReservationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        modifyReservations.setSize(new java.awt.Dimension(400, 400));

        logoSpace2.setBackground(new java.awt.Color(51, 51, 51));
        logoSpace2.setPreferredSize(new java.awt.Dimension(104, 70));

        logo7.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        logo7.setForeground(new java.awt.Color(255, 255, 255));
        logo7.setText("HYATT");

        javax.swing.GroupLayout logoSpace2Layout = new javax.swing.GroupLayout(logoSpace2);
        logoSpace2.setLayout(logoSpace2Layout);
        logoSpace2Layout.setHorizontalGroup(
            logoSpace2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoSpace2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        logoSpace2Layout.setVerticalGroup(
            logoSpace2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoSpace2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logo7)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        changeCheckInBtn.setText("Change Check In");
        changeCheckInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeCheckInBtnActionPerformed(evt);
            }
        });

        cancelReservationsBtn.setText("Cancel Reservations");
        cancelReservationsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelReservationsBtnActionPerformed(evt);
            }
        });

        changeCheckOutBtn.setText("Change Check Out");
        changeCheckOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeCheckOutBtnActionPerformed(evt);
            }
        });

        cusReservationsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(cusReservationsList);

        billBtn.setText("Total Bill");
        billBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modifyReservationsLayout = new javax.swing.GroupLayout(modifyReservations.getContentPane());
        modifyReservations.getContentPane().setLayout(modifyReservationsLayout);
        modifyReservationsLayout.setHorizontalGroup(
            modifyReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoSpace2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(modifyReservationsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modifyReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modifyReservationsLayout.createSequentialGroup()
                        .addComponent(changeCheckInBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyReservationsLayout.createSequentialGroup()
                        .addComponent(changeCheckOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyReservationsLayout.createSequentialGroup()
                        .addComponent(cancelReservationsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyReservationsLayout.createSequentialGroup()
                        .addComponent(billBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        modifyReservationsLayout.setVerticalGroup(
            modifyReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyReservationsLayout.createSequentialGroup()
                .addComponent(logoSpace2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(modifyReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modifyReservationsLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(changeCheckInBtn)
                        .addGap(18, 18, 18)
                        .addComponent(changeCheckOutBtn)
                        .addGap(18, 18, 18)
                        .addComponent(cancelReservationsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(billBtn))
                    .addGroup(modifyReservationsLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 54, Short.MAX_VALUE))
        );

        changeCheckOutFrame.setSize(new java.awt.Dimension(400, 400));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        logo9.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        logo9.setForeground(new java.awt.Color(255, 255, 255));
        logo9.setText("HYATT Staff");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo9, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(logo9)
                .addContainerGap())
        );

        jLabel12.setText("Choose new check out date:");

        newCheckOutField.setText("Change Check Out");
        newCheckOutField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newCheckOutFieldMousePressed(evt);
            }
        });
        newCheckOutField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCheckOutFieldActionPerformed(evt);
            }
        });

        confirmChangeCheckOutBtn.setText("Confirm");
        confirmChangeCheckOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmChangeCheckOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout changeCheckOutFrameLayout = new javax.swing.GroupLayout(changeCheckOutFrame.getContentPane());
        changeCheckOutFrame.getContentPane().setLayout(changeCheckOutFrameLayout);
        changeCheckOutFrameLayout.setHorizontalGroup(
            changeCheckOutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(changeCheckOutFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(changeCheckOutFrameLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(changeCheckOutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newCheckOutField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmChangeCheckOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        changeCheckOutFrameLayout.setVerticalGroup(
            changeCheckOutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeCheckOutFrameLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newCheckOutField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(confirmChangeCheckOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        changeCheckInFrame.setSize(new java.awt.Dimension(400, 400));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        logo8.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        logo8.setForeground(new java.awt.Color(255, 255, 255));
        logo8.setText("HYATT Staff");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo8, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(logo8)
                .addContainerGap())
        );

        jLabel13.setText("Choose new check out date:");

        newCheckInField.setText("Change Check In");
        newCheckInField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newCheckInFieldMousePressed(evt);
            }
        });
        newCheckInField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCheckInFieldActionPerformed(evt);
            }
        });

        confirmChangeCheckInBtn.setText("Confirm");
        confirmChangeCheckInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmChangeCheckInBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout changeCheckInFrameLayout = new javax.swing.GroupLayout(changeCheckInFrame.getContentPane());
        changeCheckInFrame.getContentPane().setLayout(changeCheckInFrameLayout);
        changeCheckInFrameLayout.setHorizontalGroup(
            changeCheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(changeCheckInFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(changeCheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addGroup(changeCheckInFrameLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(changeCheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newCheckInField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmChangeCheckInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        changeCheckInFrameLayout.setVerticalGroup(
            changeCheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeCheckInFrameLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newCheckInField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(confirmChangeCheckInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        successfulChangeFrame.setSize(new java.awt.Dimension(400, 400));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));

        logo12.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        logo12.setForeground(new java.awt.Color(255, 255, 255));
        logo12.setText("HYATT Staff");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo12, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(logo12)
                .addContainerGap())
        );

        jLabel14.setText("Your reservations has successfully been changed!");

        javax.swing.GroupLayout successfulChangeFrameLayout = new javax.swing.GroupLayout(successfulChangeFrame.getContentPane());
        successfulChangeFrame.getContentPane().setLayout(successfulChangeFrameLayout);
        successfulChangeFrameLayout.setHorizontalGroup(
            successfulChangeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(successfulChangeFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        successfulChangeFrameLayout.setVerticalGroup(
            successfulChangeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successfulChangeFrameLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 147, Short.MAX_VALUE))
        );

        billFrame.setSize(new java.awt.Dimension(400, 400));

        logoSpace3.setBackground(new java.awt.Color(51, 51, 51));
        logoSpace3.setPreferredSize(new java.awt.Dimension(104, 70));

        logo10.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        logo10.setForeground(new java.awt.Color(255, 255, 255));
        logo10.setText("HYATT");

        javax.swing.GroupLayout logoSpace3Layout = new javax.swing.GroupLayout(logoSpace3);
        logoSpace3.setLayout(logoSpace3Layout);
        logoSpace3Layout.setHorizontalGroup(
            logoSpace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoSpace3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        logoSpace3Layout.setVerticalGroup(
            logoSpace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoSpace3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logo10)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel15.setText("Your total amount was: ");

        javax.swing.GroupLayout billFrameLayout = new javax.swing.GroupLayout(billFrame.getContentPane());
        billFrame.getContentPane().setLayout(billFrameLayout);
        billFrameLayout.setHorizontalGroup(
            billFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoSpace3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(billFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        billFrameLayout.setVerticalGroup(
            billFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billFrameLayout.createSequentialGroup()
                .addComponent(logoSpace3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 151, Short.MAX_VALUE))
        );

        canceledRes.setSize(new java.awt.Dimension(400, 400));

        logoSpace4.setBackground(new java.awt.Color(51, 51, 51));
        logoSpace4.setPreferredSize(new java.awt.Dimension(104, 70));

        logo11.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        logo11.setForeground(new java.awt.Color(255, 255, 255));
        logo11.setText("HYATT");

        javax.swing.GroupLayout logoSpace4Layout = new javax.swing.GroupLayout(logoSpace4);
        logoSpace4.setLayout(logoSpace4Layout);
        logoSpace4Layout.setHorizontalGroup(
            logoSpace4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoSpace4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        logoSpace4Layout.setVerticalGroup(
            logoSpace4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoSpace4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logo11)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel16.setText("You have canceled your reservations, sadly :(");

        javax.swing.GroupLayout canceledResLayout = new javax.swing.GroupLayout(canceledRes.getContentPane());
        canceledRes.getContentPane().setLayout(canceledResLayout);
        canceledResLayout.setHorizontalGroup(
            canceledResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoSpace4, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(canceledResLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        canceledResLayout.setVerticalGroup(
            canceledResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(canceledResLayout.createSequentialGroup()
                .addComponent(logoSpace4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 100, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(200, 200));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setSize(new java.awt.Dimension(400, 400));

        logo.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HYATT ");

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        findHotelsBtn.setBackground(new java.awt.Color(255, 255, 255));
        findHotelsBtn.setText("Find Hotels");
        findHotelsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findHotelsBtnActionPerformed(evt);
            }
        });

        cityHotelList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings =  hotel.getLocations();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        cityHotelList.setPreferredSize(new java.awt.Dimension(50, 50));
        jScrollPane1.setViewportView(cityHotelList);

        haveReservationsBtn.setText("Have Reservations?");
        haveReservationsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haveReservationsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(findHotelsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(haveReservationsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(findHotelsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(haveReservationsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findHotelsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findHotelsBtnActionPerformed
        // TODO add your handling code here:
        chosenLocation = cityHotelList.getSelectedValue(); 
//        hotel.getAreaHotels(chosenLocation);
        this.setVisible(false);
        viewAreaHotels.setVisible(true);
        
        areaHotelsList.setListData(hotel.getAreaHotels(chosenLocation)); 
    }//GEN-LAST:event_findHotelsBtnActionPerformed

    private void selectHotelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectHotelBtnActionPerformed
        // TODO add your handling code here:
        String chosenHotel = areaHotelsList.getSelectedValue();
        System.out.println("thisis"+chosenHotel);
        viewAreaHotels.setVisible(false);
        viewHotelRooms.setVisible(true);
        
        roomsList.setListData(hotel.getHotelRooms(chosenHotel, chosenLocation));
 //       roomsList.setVisible(true);
    
    }//GEN-LAST:event_selectHotelBtnActionPerformed

    private void selectRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectRoomBtnActionPerformed
        // TODO add your handling code here:
        String chosenRoom = roomsList.getSelectedValue();
        System.out.println(chosenRoom);
        viewHotelRooms.setVisible(false);
        createReservations.setVisible(true);
    }//GEN-LAST:event_selectRoomBtnActionPerformed

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed
  
    private void NameFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameFieldMousePressed
        // TODO add your handling code here:
        NameField.setText("");
    }//GEN-LAST:event_NameFieldMousePressed

    private void creditNumFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditNumFieldMousePressed
        // TODO add your handling code here:
        creditNumField.setText("");
    }//GEN-LAST:event_creditNumFieldMousePressed

    private void cardCodeFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardCodeFieldMousePressed
        // TODO add your handling code here:
        cardCodeField.setText("");
    }//GEN-LAST:event_cardCodeFieldMousePressed

    private void createResBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createResBtnActionPerformed
        // TODO add your handling code here:
        String chosenHotel = areaHotelsList.getSelectedValue();
        createReservations.setVisible(false);
        confirmReservations.setVisible(true);
            
        nameLabel.setText(NameField.getText());
        reservationsLabel.setText(checkInField.getText() + " - " + checkOutField.getText());
        
        String chosenRoom = roomsList.getSelectedValue();
        roomTypeLabel.setText(chosenRoom.substring(0,6));
        
        atLabel.setText(chosenHotel + " - "+ chosenLocation);
        
    }//GEN-LAST:event_createResBtnActionPerformed

    private void checkOutFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkOutFieldActionPerformed

    private void checkInFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkInFieldMousePressed
        // TODO add your handling code here:
        checkInField.setText("");
    }//GEN-LAST:event_checkInFieldMousePressed

    private void checkOutFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkOutFieldMousePressed
        // TODO add your handling code here:
        checkOutField.setText("");
    }//GEN-LAST:event_checkOutFieldMousePressed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
        String name = NameField.getText();
        String checkIn = checkInField.getText();
        String checkOut = checkOutField.getText();
        String creditCard = creditNumField.getText();
        String CCV = cardCodeField.getText();
        String chosenHotel = areaHotelsList.getSelectedValue();
        String city = cityHotelList.getSelectedValue();
        String room_type = roomsList.getSelectedValue();
        
        
        Customer customer = new Customer(name, checkIn, checkOut, creditCard, CCV, chosenHotel, city, room_type);
        
        try {
            hotel.insertCustomer(customer);
        } catch (ParseException ex) {
            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        confirmReservations.setVisible(false);
        
        reservationsMade.setVisible(true);
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void haveReservationsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haveReservationsBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        cusReservationFrame.setVisible(true);
    }//GEN-LAST:event_haveReservationsBtnActionPerformed

    private void changeCheckInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeCheckInBtnActionPerformed
        // TODO add your handling code here:
        changeCheckInFrame.setVisible(true);
        modifyReservations.setVisible(false);
    }//GEN-LAST:event_changeCheckInBtnActionPerformed

    private void cancelReservationsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelReservationsBtnActionPerformed
        // TODO add your handling code here:
        modifyReservations.setVisible(false);
        try {
            hotel.cancelReservations(cusReservationsList.getSelectedValue());
        } catch (SQLException ex) {
            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        canceledRes.setVisible(true);
        

    }//GEN-LAST:event_cancelReservationsBtnActionPerformed

    private void changeCheckOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeCheckOutBtnActionPerformed
        // TODO add your handling code here:
        changeCheckOutFrame.setVisible(true);
        modifyReservations.setVisible(false);
    }//GEN-LAST:event_changeCheckOutBtnActionPerformed

    private void viewReservationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReservationBtnActionPerformed
        // TODO add your handling code here:
        cusReservationFrame.setVisible(false);
        modifyReservations.setVisible(true);
        cusReservationsList.setListData(hotel.showUser(searchNameField.getText()));
        cusReservationsList.setFixedCellHeight(30);
    }//GEN-LAST:event_viewReservationBtnActionPerformed

    private void searchNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchNameFieldActionPerformed

    private void newCheckOutFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newCheckOutFieldMousePressed
        // TODO add your handling code here:
        newCheckOutField.setText("");
    }//GEN-LAST:event_newCheckOutFieldMousePressed

    private void newCheckOutFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCheckOutFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCheckOutFieldActionPerformed

    private void confirmChangeCheckOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmChangeCheckOutBtnActionPerformed
        try {
            // TODO add your handling code here:
            hotel.changeCheckOut(newCheckOutField.getText(), searchNameField.getText());

        } catch (ParseException | SQLException ex) {
            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        changeCheckOutFrame.setVisible(false);
        successfulChangeFrame.setVisible(true);
    }//GEN-LAST:event_confirmChangeCheckOutBtnActionPerformed

    private void newCheckInFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newCheckInFieldMousePressed
        // TODO add your handling code here:
        newCheckInField.setText("");
    }//GEN-LAST:event_newCheckInFieldMousePressed

    private void newCheckInFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCheckInFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCheckInFieldActionPerformed

    private void confirmChangeCheckInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmChangeCheckInBtnActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            hotel.changeCheckIn(newCheckInField.getText(), searchNameField.getText());

        } catch (ParseException | SQLException ex) {
            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        changeCheckInFrame.setVisible(false);
        successfulChangeFrame.setVisible(true);
    }//GEN-LAST:event_confirmChangeCheckInBtnActionPerformed

    private void billBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billBtnActionPerformed
        // TODO add your handling code here:
        modifyReservations.setVisible(false);
        billFrame.setVisible(true);
        Client client = new Client();
        String bill = client.getBill();
        jLabel15.setText("Your total bill is: "+ bill);
    }//GEN-LAST:event_billBtnActionPerformed
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI().setVisible(true);
            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NameField;
    private javax.swing.JList<String> areaHotelsList;
    private javax.swing.JLabel atLabel;
    private javax.swing.JButton billBtn;
    private javax.swing.JFrame billFrame;
    private javax.swing.JButton cancelReservationsBtn;
    private javax.swing.JFrame canceledRes;
    private javax.swing.JTextField cardCodeField;
    private javax.swing.JButton changeCheckInBtn;
    private javax.swing.JFrame changeCheckInFrame;
    private javax.swing.JButton changeCheckOutBtn;
    private javax.swing.JFrame changeCheckOutFrame;
    private javax.swing.JTextField checkInField;
    private javax.swing.JTextField checkOutField;
    private javax.swing.JList<String> cityHotelList;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JButton confirmChangeCheckInBtn;
    private javax.swing.JButton confirmChangeCheckOutBtn;
    private javax.swing.JFrame confirmReservations;
    private javax.swing.JButton createResBtn;
    private javax.swing.JLabel createResLabel;
    private javax.swing.JFrame createReservations;
    private javax.swing.JTextField creditNumField;
    private javax.swing.JFrame cusReservationFrame;
    private javax.swing.JList<String> cusReservationsList;
    private javax.swing.JButton findHotelsBtn;
    private javax.swing.JButton haveReservationsBtn;
    private javax.swing.JLabel hotelListLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel logo;
    private javax.swing.JLabel logo10;
    private javax.swing.JLabel logo11;
    private javax.swing.JLabel logo12;
    private javax.swing.JPanel logo2;
    private javax.swing.JPanel logo3;
    private javax.swing.JLabel logo5;
    private javax.swing.JLabel logo6;
    private javax.swing.JLabel logo7;
    private javax.swing.JLabel logo8;
    private javax.swing.JLabel logo9;
    private javax.swing.JPanel logoSpace;
    private javax.swing.JPanel logoSpace1;
    private javax.swing.JPanel logoSpace2;
    private javax.swing.JPanel logoSpace3;
    private javax.swing.JPanel logoSpace4;
    private javax.swing.JFrame modifyReservations;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField newCheckInField;
    private javax.swing.JTextField newCheckOutField;
    private javax.swing.JLabel reservationsLabel;
    private javax.swing.JFrame reservationsMade;
    private javax.swing.JLabel roomTypeLabel;
    private javax.swing.JList<String> roomsList;
    private javax.swing.JTextField searchNameField;
    private javax.swing.JButton selectHotelBtn;
    private javax.swing.JButton selectRoomBtn;
    private javax.swing.JFrame successfulChangeFrame;
    private javax.swing.JFrame viewAreaHotels;
    private javax.swing.JFrame viewHotelRooms;
    private javax.swing.JButton viewReservationBtn;
    // End of variables declaration//GEN-END:variables
}
