package ServerSide;

import java.sql.SQLException;
import java.text.ParseException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luis
 */
public class ServerGUI extends javax.swing.JFrame {
    DBConnect staff = new DBConnect();
    /**
     * Creates new form ServerGUI
     */
    public ServerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewReservationsFrame = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewReservationsList = new javax.swing.JList<>();
        checkInBtn = new javax.swing.JButton();
        checkOutBtn = new javax.swing.JButton();
        changeCheckInBtn = new javax.swing.JButton();
        cancelReservationsBtn = new javax.swing.JButton();
        changeCheckOutBtn = new javax.swing.JButton();
        cancelReservationsFrame = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        logo7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        changeCheckOutFrame = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        logo9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        newCheckOutField = new javax.swing.JTextField();
        confirmChangeCheckOutBtn = new javax.swing.JButton();
        changeCheckInFrame = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        logo8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        newCheckInField = new javax.swing.JTextField();
        confirmChangeCheckInBtn = new javax.swing.JButton();
        checkInFrame = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        logo10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        checkOutFrame = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        logo11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        successfulChangeFrame = new javax.swing.JFrame();
        jPanel8 = new javax.swing.JPanel();
        logo12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        showCusChangeCheckInFrame = new javax.swing.JFrame();
        jPanel11 = new javax.swing.JPanel();
        logo15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        customerInfoList = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        yesChangeCheckInBtn = new javax.swing.JButton();
        noChangeCheckInBtn = new javax.swing.JButton();
        showCusChangeCheckOutFrame = new javax.swing.JFrame();
        jPanel12 = new javax.swing.JPanel();
        logo16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        customerInfoList1 = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        yesChangeCheckOutBtn = new javax.swing.JButton();
        noChangeCheckOutBtn = new javax.swing.JButton();
        showCusCancelResFrame = new javax.swing.JFrame();
        jPanel13 = new javax.swing.JPanel();
        logo17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        customerInfoList2 = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        yesCancelResBtn = new javax.swing.JButton();
        noCancelResBtn = new javax.swing.JButton();
        showCusCheckInFrame = new javax.swing.JFrame();
        jPanel14 = new javax.swing.JPanel();
        logo18 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        customerInfoList3 = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        yesCheckInBtn = new javax.swing.JButton();
        noCheckInBtn = new javax.swing.JButton();
        showCusCheckOutFrame = new javax.swing.JFrame();
        jPanel15 = new javax.swing.JPanel();
        logo19 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        customerInfoList4 = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        yesCheckOutBtn = new javax.swing.JButton();
        noCheckOutBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        logo6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        viewReservationsBtn = new javax.swing.JButton();

        viewReservationsFrame.setSize(new java.awt.Dimension(480, 400));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HYATT Staff");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        viewReservationsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(viewReservationsList);

        checkInBtn.setText("Check In");
        checkInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInBtnActionPerformed(evt);
            }
        });

        checkOutBtn.setText("Check Out");
        checkOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutBtnActionPerformed(evt);
            }
        });

        changeCheckInBtn.setText("Change Check In");
        changeCheckInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeCheckInBtnActionPerformed(evt);
            }
        });

        cancelReservationsBtn.setText("Cancel Reservations");
        cancelReservationsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelReservationsBtnActionPerformed(evt);
            }
        });

        changeCheckOutBtn.setText("Change Check Out");
        changeCheckOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeCheckOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewReservationsFrameLayout = new javax.swing.GroupLayout(viewReservationsFrame.getContentPane());
        viewReservationsFrame.getContentPane().setLayout(viewReservationsFrameLayout);
        viewReservationsFrameLayout.setHorizontalGroup(
            viewReservationsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(viewReservationsFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewReservationsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkInBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changeCheckInBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelReservationsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(changeCheckOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        viewReservationsFrameLayout.setVerticalGroup(
            viewReservationsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewReservationsFrameLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(viewReservationsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewReservationsFrameLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1))
                    .addGroup(viewReservationsFrameLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(checkInBtn)
                        .addGap(18, 18, 18)
                        .addComponent(checkOutBtn)
                        .addGap(18, 18, 18)
                        .addComponent(changeCheckInBtn)
                        .addGap(18, 18, 18)
                        .addComponent(changeCheckOutBtn)
                        .addGap(18, 18, 18)
                        .addComponent(cancelReservationsBtn)
                        .addContainerGap(52, Short.MAX_VALUE))))
        );

        cancelReservationsFrame.setSize(new java.awt.Dimension(400, 400));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        logo7.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        logo7.setForeground(new java.awt.Color(255, 255, 255));
        logo7.setText("HYATT Staff");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo7, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(logo7)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Your reservations have been canceled :((");

        javax.swing.GroupLayout cancelReservationsFrameLayout = new javax.swing.GroupLayout(cancelReservationsFrame.getContentPane());
        cancelReservationsFrame.getContentPane().setLayout(cancelReservationsFrameLayout);
        cancelReservationsFrameLayout.setHorizontalGroup(
            cancelReservationsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        cancelReservationsFrameLayout.setVerticalGroup(
            cancelReservationsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelReservationsFrameLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 107, Short.MAX_VALUE))
        );

        changeCheckOutFrame.setSize(new java.awt.Dimension(400, 400));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        logo9.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        logo9.setForeground(new java.awt.Color(255, 255, 255));
        logo9.setText("HYATT Staff");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo9, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(logo9)
                .addContainerGap())
        );

        jLabel4.setText("Choose new check out date:");

        newCheckOutField.setText("Change Check Out");
        newCheckOutField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newCheckOutFieldMousePressed(evt);
            }
        });
        newCheckOutField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCheckOutFieldActionPerformed(evt);
            }
        });

        confirmChangeCheckOutBtn.setText("Confirm");
        confirmChangeCheckOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmChangeCheckOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout changeCheckOutFrameLayout = new javax.swing.GroupLayout(changeCheckOutFrame.getContentPane());
        changeCheckOutFrame.getContentPane().setLayout(changeCheckOutFrameLayout);
        changeCheckOutFrameLayout.setHorizontalGroup(
            changeCheckOutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(changeCheckOutFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(changeCheckOutFrameLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(changeCheckOutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newCheckOutField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmChangeCheckOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        changeCheckOutFrameLayout.setVerticalGroup(
            changeCheckOutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeCheckOutFrameLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newCheckOutField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(confirmChangeCheckOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        changeCheckInFrame.setSize(new java.awt.Dimension(400, 400));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        logo8.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        logo8.setForeground(new java.awt.Color(255, 255, 255));
        logo8.setText("HYATT Staff");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo8, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(logo8)
                .addContainerGap())
        );

        jLabel6.setText("Choose new check out date:");

        newCheckInField.setText("Change Check In");
        newCheckInField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newCheckInFieldMousePressed(evt);
            }
        });
        newCheckInField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCheckInFieldActionPerformed(evt);
            }
        });

        confirmChangeCheckInBtn.setText("Confirm");
        confirmChangeCheckInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmChangeCheckInBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout changeCheckInFrameLayout = new javax.swing.GroupLayout(changeCheckInFrame.getContentPane());
        changeCheckInFrame.getContentPane().setLayout(changeCheckInFrameLayout);
        changeCheckInFrameLayout.setHorizontalGroup(
            changeCheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(changeCheckInFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(changeCheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addGroup(changeCheckInFrameLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(changeCheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newCheckInField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmChangeCheckInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        changeCheckInFrameLayout.setVerticalGroup(
            changeCheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeCheckInFrameLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newCheckInField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(confirmChangeCheckInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        checkInFrame.setSize(new java.awt.Dimension(400, 400));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        logo10.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        logo10.setForeground(new java.awt.Color(255, 255, 255));
        logo10.setText("HYATT Staff");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo10, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(logo10)
                .addContainerGap())
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Sending Customer,");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("greetings, room number, and keys");

        javax.swing.GroupLayout checkInFrameLayout = new javax.swing.GroupLayout(checkInFrame.getContentPane());
        checkInFrame.getContentPane().setLayout(checkInFrameLayout);
        checkInFrameLayout.setHorizontalGroup(
            checkInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(checkInFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkInFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        checkInFrameLayout.setVerticalGroup(
            checkInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkInFrameLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        checkOutFrame.setSize(new java.awt.Dimension(400, 400));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        logo11.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        logo11.setForeground(new java.awt.Color(255, 255, 255));
        logo11.setText("HYATT Staff");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo11, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(logo11)
                .addContainerGap())
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Sending Customer,");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("their bill through the network...");

        javax.swing.GroupLayout checkOutFrameLayout = new javax.swing.GroupLayout(checkOutFrame.getContentPane());
        checkOutFrame.getContentPane().setLayout(checkOutFrameLayout);
        checkOutFrameLayout.setHorizontalGroup(
            checkOutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(checkOutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(checkOutFrameLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(checkOutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(checkOutFrameLayout.createSequentialGroup()
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkOutFrameLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        checkOutFrameLayout.setVerticalGroup(
            checkOutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkOutFrameLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 240, Short.MAX_VALUE))
            .addGroup(checkOutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(checkOutFrameLayout.createSequentialGroup()
                    .addGap(101, 101, 101)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(111, Short.MAX_VALUE)))
        );

        successfulChangeFrame.setSize(new java.awt.Dimension(400, 400));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));

        logo12.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        logo12.setForeground(new java.awt.Color(255, 255, 255));
        logo12.setText("HYATT Staff");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo12, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(logo12)
                .addContainerGap())
        );

        jLabel5.setText("Your reservations has successfully been changed!");

        javax.swing.GroupLayout successfulChangeFrameLayout = new javax.swing.GroupLayout(successfulChangeFrame.getContentPane());
        successfulChangeFrame.getContentPane().setLayout(successfulChangeFrameLayout);
        successfulChangeFrameLayout.setHorizontalGroup(
            successfulChangeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(successfulChangeFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        successfulChangeFrameLayout.setVerticalGroup(
            successfulChangeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successfulChangeFrameLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 147, Short.MAX_VALUE))
        );

        showCusChangeCheckInFrame.setSize(new java.awt.Dimension(400, 400));

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));

        logo15.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        logo15.setForeground(new java.awt.Color(255, 255, 255));
        logo15.setText("HYATT Staff");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo15, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(logo15)
                .addContainerGap())
        );

        customerInfoList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(customerInfoList);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Is it this Customer?");

        yesChangeCheckInBtn.setText("Yes!");
        yesChangeCheckInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesChangeCheckInBtnActionPerformed(evt);
            }
        });

        noChangeCheckInBtn.setText("No!");
        noChangeCheckInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noChangeCheckInBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout showCusChangeCheckInFrameLayout = new javax.swing.GroupLayout(showCusChangeCheckInFrame.getContentPane());
        showCusChangeCheckInFrame.getContentPane().setLayout(showCusChangeCheckInFrameLayout);
        showCusChangeCheckInFrameLayout.setHorizontalGroup(
            showCusChangeCheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(showCusChangeCheckInFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showCusChangeCheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(showCusChangeCheckInFrameLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(showCusChangeCheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yesChangeCheckInBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noChangeCheckInBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(showCusChangeCheckInFrameLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        showCusChangeCheckInFrameLayout.setVerticalGroup(
            showCusChangeCheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showCusChangeCheckInFrameLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(showCusChangeCheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(showCusChangeCheckInFrameLayout.createSequentialGroup()
                        .addComponent(yesChangeCheckInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(noChangeCheckInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        showCusChangeCheckOutFrame.setSize(new java.awt.Dimension(400, 400));

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));

        logo16.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        logo16.setForeground(new java.awt.Color(255, 255, 255));
        logo16.setText("HYATT Staff");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo16, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(logo16)
                .addContainerGap())
        );

        customerInfoList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(customerInfoList1);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Is it this Customer?");

        yesChangeCheckOutBtn.setText("Yes!");
        yesChangeCheckOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesChangeCheckOutBtnActionPerformed(evt);
            }
        });

        noChangeCheckOutBtn.setText("No!");
        noChangeCheckOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noChangeCheckOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout showCusChangeCheckOutFrameLayout = new javax.swing.GroupLayout(showCusChangeCheckOutFrame.getContentPane());
        showCusChangeCheckOutFrame.getContentPane().setLayout(showCusChangeCheckOutFrameLayout);
        showCusChangeCheckOutFrameLayout.setHorizontalGroup(
            showCusChangeCheckOutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(showCusChangeCheckOutFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showCusChangeCheckOutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(showCusChangeCheckOutFrameLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(showCusChangeCheckOutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yesChangeCheckOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noChangeCheckOutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(showCusChangeCheckOutFrameLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        showCusChangeCheckOutFrameLayout.setVerticalGroup(
            showCusChangeCheckOutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showCusChangeCheckOutFrameLayout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(showCusChangeCheckOutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(showCusChangeCheckOutFrameLayout.createSequentialGroup()
                        .addComponent(yesChangeCheckOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(noChangeCheckOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        showCusCancelResFrame.setSize(new java.awt.Dimension(400, 400));

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));

        logo17.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        logo17.setForeground(new java.awt.Color(255, 255, 255));
        logo17.setText("HYATT Staff");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo17, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(logo17)
                .addContainerGap())
        );

        customerInfoList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(customerInfoList2);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Are you sure you want to cancel this reservation?");

        yesCancelResBtn.setText("Yes!");
        yesCancelResBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesCancelResBtnActionPerformed(evt);
            }
        });

        noCancelResBtn.setText("No!");
        noCancelResBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noCancelResBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout showCusCancelResFrameLayout = new javax.swing.GroupLayout(showCusCancelResFrame.getContentPane());
        showCusCancelResFrame.getContentPane().setLayout(showCusCancelResFrameLayout);
        showCusCancelResFrameLayout.setHorizontalGroup(
            showCusCancelResFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(showCusCancelResFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showCusCancelResFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(showCusCancelResFrameLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(showCusCancelResFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yesCancelResBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noCancelResBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        showCusCancelResFrameLayout.setVerticalGroup(
            showCusCancelResFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showCusCancelResFrameLayout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(showCusCancelResFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(showCusCancelResFrameLayout.createSequentialGroup()
                        .addComponent(yesCancelResBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(noCancelResBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        showCusCheckInFrame.setSize(new java.awt.Dimension(400, 400));

        jPanel14.setBackground(new java.awt.Color(51, 51, 51));

        logo18.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        logo18.setForeground(new java.awt.Color(255, 255, 255));
        logo18.setText("HYATT Staff");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo18, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(logo18)
                .addContainerGap())
        );

        customerInfoList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(customerInfoList3);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Is it this Customer?");

        yesCheckInBtn.setText("Check In!");
        yesCheckInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesCheckInBtnActionPerformed(evt);
            }
        });

        noCheckInBtn.setText("No!");
        noCheckInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noCheckInBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout showCusCheckInFrameLayout = new javax.swing.GroupLayout(showCusCheckInFrame.getContentPane());
        showCusCheckInFrame.getContentPane().setLayout(showCusCheckInFrameLayout);
        showCusCheckInFrameLayout.setHorizontalGroup(
            showCusCheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(showCusCheckInFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showCusCheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(showCusCheckInFrameLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(showCusCheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yesCheckInBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noCheckInBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(showCusCheckInFrameLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        showCusCheckInFrameLayout.setVerticalGroup(
            showCusCheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showCusCheckInFrameLayout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(showCusCheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(showCusCheckInFrameLayout.createSequentialGroup()
                        .addComponent(yesCheckInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(noCheckInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        showCusCheckOutFrame.setSize(new java.awt.Dimension(400, 400));

        jPanel15.setBackground(new java.awt.Color(51, 51, 51));

        logo19.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        logo19.setForeground(new java.awt.Color(255, 255, 255));
        logo19.setText("HYATT Staff");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo19, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(logo19)
                .addContainerGap())
        );

        customerInfoList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(customerInfoList4);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Is it this Customer?");

        yesCheckOutBtn.setText("Check Out!");
        yesCheckOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesCheckOutBtnActionPerformed(evt);
            }
        });

        noCheckOutBtn.setText("No!");
        noCheckOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noCheckOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout showCusCheckOutFrameLayout = new javax.swing.GroupLayout(showCusCheckOutFrame.getContentPane());
        showCusCheckOutFrame.getContentPane().setLayout(showCusCheckOutFrameLayout);
        showCusCheckOutFrameLayout.setHorizontalGroup(
            showCusCheckOutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(showCusCheckOutFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showCusCheckOutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(showCusCheckOutFrameLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(showCusCheckOutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yesCheckOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noCheckOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(showCusCheckOutFrameLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        showCusCheckOutFrameLayout.setVerticalGroup(
            showCusCheckOutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showCusCheckOutFrameLayout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(showCusCheckOutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(showCusCheckOutFrameLayout.createSequentialGroup()
                        .addComponent(yesCheckOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(noCheckOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        logo6.setFont(new java.awt.Font("Mshtakan", 2, 24)); // NOI18N
        logo6.setForeground(new java.awt.Color(255, 255, 255));
        logo6.setText("HYATT Staff");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(logo6)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Al Bayan", 3, 18)); // NOI18N
        jLabel2.setText("Per Customer Request...");

        viewReservationsBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        viewReservationsBtn.setText("View Reservations");
        viewReservationsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReservationsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewReservationsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(viewReservationsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewReservationsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReservationsBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        viewReservationsFrame.setVisible(true);
        viewReservationsList.setListData(staff.viewReservations());
        viewReservationsList.setFixedCellHeight(30);
    }//GEN-LAST:event_viewReservationsBtnActionPerformed

    private void checkOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutBtnActionPerformed
        // TODO add your handling code here:
        viewReservationsFrame.setVisible(false);
        showCusCheckOutFrame.setVisible(true);
        customerInfoList4.setListData(staff.showUser(viewReservationsList.getSelectedValue()));
        customerInfoList4.setFixedCellHeight(30);
    }//GEN-LAST:event_checkOutBtnActionPerformed

    private void cancelReservationsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelReservationsBtnActionPerformed
        // TODO add your handling code here:
        viewReservationsFrame.setVisible(false);
        showCusCancelResFrame.setVisible(true);
        customerInfoList2.setListData(staff.showUser(viewReservationsList.getSelectedValue()));
        customerInfoList2.setFixedCellHeight(30);
        
    }//GEN-LAST:event_cancelReservationsBtnActionPerformed

    private void changeCheckInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeCheckInBtnActionPerformed
        // TODO add your handling code here:
        viewReservationsFrame.setVisible(false);
        showCusChangeCheckInFrame.setVisible(true);
        customerInfoList.setListData(staff.showUser(viewReservationsList.getSelectedValue()));
        customerInfoList.setFixedCellHeight(30);
    }//GEN-LAST:event_changeCheckInBtnActionPerformed

    private void changeCheckOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeCheckOutBtnActionPerformed
        // TODO add your handling code here:
        viewReservationsFrame.setVisible(false);
        showCusChangeCheckOutFrame.setVisible(true);
        customerInfoList1.setListData(staff.showUser(viewReservationsList.getSelectedValue()));
        customerInfoList1.setFixedCellHeight(30);
    }//GEN-LAST:event_changeCheckOutBtnActionPerformed

    private void newCheckOutFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCheckOutFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCheckOutFieldActionPerformed

    private void confirmChangeCheckOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmChangeCheckOutBtnActionPerformed
        try {
            // TODO add your handling code here:
            staff.changeCheckOut(newCheckOutField.getText(), viewReservationsList.getSelectedValue());
            
        } catch (ParseException | SQLException ex) {
            Logger.getLogger(ServerGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        changeCheckOutFrame.setVisible(false);
        successfulChangeFrame.setVisible(true);
    }//GEN-LAST:event_confirmChangeCheckOutBtnActionPerformed

    private void newCheckInFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCheckInFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCheckInFieldActionPerformed

    private void confirmChangeCheckInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmChangeCheckInBtnActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            staff.changeCheckIn(newCheckInField.getText(), viewReservationsList.getSelectedValue());
            
        } catch (ParseException | SQLException ex) {
            Logger.getLogger(ServerGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        changeCheckInFrame.setVisible(false);
        successfulChangeFrame.setVisible(true);
    }//GEN-LAST:event_confirmChangeCheckInBtnActionPerformed

    private void newCheckInFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newCheckInFieldMousePressed
        // TODO add your handling code here:
        newCheckInField.setText("");
    }//GEN-LAST:event_newCheckInFieldMousePressed

    private void newCheckOutFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newCheckOutFieldMousePressed
        // TODO add your handling code here:
        newCheckOutField.setText("");
    }//GEN-LAST:event_newCheckOutFieldMousePressed

    private void yesChangeCheckInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesChangeCheckInBtnActionPerformed
        // TODO add your handling code here:
        showCusChangeCheckInFrame.setVisible(false);
        changeCheckInFrame.setVisible(true);
    }//GEN-LAST:event_yesChangeCheckInBtnActionPerformed

    private void yesChangeCheckOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesChangeCheckOutBtnActionPerformed
        // TODO add your handling code here:
        showCusChangeCheckOutFrame.setVisible(false);
        changeCheckInFrame.setVisible(true);
    }//GEN-LAST:event_yesChangeCheckOutBtnActionPerformed

    private void yesCancelResBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesCancelResBtnActionPerformed
        // TODO add your handling code here:
        showCusCancelResFrame.setVisible(false);
        try {
            staff.cancelReservations(viewReservationsList.getSelectedValue());
        } catch (SQLException ex) {
            Logger.getLogger(ServerGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        cancelReservationsFrame.setVisible(true);
    }//GEN-LAST:event_yesCancelResBtnActionPerformed

    private void yesCheckInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesCheckInBtnActionPerformed
        // TODO add your handling code here:
        showCusCheckInFrame.setVisible(false);
        checkInFrame.setVisible(true);
    }//GEN-LAST:event_yesCheckInBtnActionPerformed

    private void yesCheckOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesCheckOutBtnActionPerformed
        // TODO add your handling code here:
        showCusCheckOutFrame.setVisible(false);
        checkOutFrame.setVisible(true);
        staff.checkOut(viewReservationsList.getSelectedValue());
        Server server = new Server();
        
    }//GEN-LAST:event_yesCheckOutBtnActionPerformed

    private void checkInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInBtnActionPerformed
        // TODO add your handling code here:
        viewReservationsFrame.setVisible(false);
        showCusCheckInFrame.setVisible(true);
        customerInfoList3.setListData(staff.showUser(viewReservationsList.getSelectedValue()));
        customerInfoList3.setFixedCellHeight(30);
    }//GEN-LAST:event_checkInBtnActionPerformed

    private void noCheckInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noCheckInBtnActionPerformed
        // TODO add your handling code here:
        showCusCheckInFrame.setVisible(false);
        viewReservationsFrame.setVisible(true);
    }//GEN-LAST:event_noCheckInBtnActionPerformed

    private void noCheckOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noCheckOutBtnActionPerformed
        // TODO add your handling code here:
        showCusCheckInFrame.setVisible(false);
        viewReservationsFrame.setVisible(true);
    }//GEN-LAST:event_noCheckOutBtnActionPerformed

    private void noCancelResBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noCancelResBtnActionPerformed
        // TODO add your handling code here:
        showCusCancelResFrame.setVisible(false);
        viewReservationsFrame.setVisible(true);
    }//GEN-LAST:event_noCancelResBtnActionPerformed

    private void noChangeCheckOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noChangeCheckOutBtnActionPerformed
        // TODO add your handling code here:
        showCusChangeCheckOutFrame.setVisible(false);
        viewReservationsFrame.setVisible(true);
    }//GEN-LAST:event_noChangeCheckOutBtnActionPerformed

    private void noChangeCheckInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noChangeCheckInBtnActionPerformed
        // TODO add your handling code here:
        showCusChangeCheckInFrame.setVisible(false);
        viewReservationsFrame.setVisible(true);
    }//GEN-LAST:event_noChangeCheckInBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelReservationsBtn;
    private javax.swing.JFrame cancelReservationsFrame;
    private javax.swing.JButton changeCheckInBtn;
    private javax.swing.JFrame changeCheckInFrame;
    private javax.swing.JButton changeCheckOutBtn;
    private javax.swing.JFrame changeCheckOutFrame;
    private javax.swing.JButton checkInBtn;
    private javax.swing.JFrame checkInFrame;
    private javax.swing.JButton checkOutBtn;
    private javax.swing.JFrame checkOutFrame;
    private javax.swing.JButton confirmChangeCheckInBtn;
    private javax.swing.JButton confirmChangeCheckOutBtn;
    private javax.swing.JList<String> customerInfoList;
    private javax.swing.JList<String> customerInfoList1;
    private javax.swing.JList<String> customerInfoList2;
    private javax.swing.JList<String> customerInfoList3;
    private javax.swing.JList<String> customerInfoList4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel logo10;
    private javax.swing.JLabel logo11;
    private javax.swing.JLabel logo12;
    private javax.swing.JLabel logo15;
    private javax.swing.JLabel logo16;
    private javax.swing.JLabel logo17;
    private javax.swing.JLabel logo18;
    private javax.swing.JLabel logo19;
    private javax.swing.JLabel logo6;
    private javax.swing.JLabel logo7;
    private javax.swing.JLabel logo8;
    private javax.swing.JLabel logo9;
    private javax.swing.JTextField newCheckInField;
    private javax.swing.JTextField newCheckOutField;
    private javax.swing.JButton noCancelResBtn;
    private javax.swing.JButton noChangeCheckInBtn;
    private javax.swing.JButton noChangeCheckOutBtn;
    private javax.swing.JButton noCheckInBtn;
    private javax.swing.JButton noCheckOutBtn;
    private javax.swing.JFrame showCusCancelResFrame;
    private javax.swing.JFrame showCusChangeCheckInFrame;
    private javax.swing.JFrame showCusChangeCheckOutFrame;
    private javax.swing.JFrame showCusCheckInFrame;
    private javax.swing.JFrame showCusCheckOutFrame;
    private javax.swing.JFrame successfulChangeFrame;
    private javax.swing.JButton viewReservationsBtn;
    private javax.swing.JFrame viewReservationsFrame;
    private javax.swing.JList<String> viewReservationsList;
    private javax.swing.JButton yesCancelResBtn;
    private javax.swing.JButton yesChangeCheckInBtn;
    private javax.swing.JButton yesChangeCheckOutBtn;
    private javax.swing.JButton yesCheckInBtn;
    private javax.swing.JButton yesCheckOutBtn;
    // End of variables declaration//GEN-END:variables
}
